### ISSUE TITLE
Script failing on 17.9.3

### ISSUE THREAD

**Issue by JesusPavonCBRE** [dot11zen/9800-NETCONF-script#1]
I'm using your script as example to use NETCONF and I've noticed that only some calls works (like  'get_full_config(m)') and some others return error (like 'ap_list = get_tags_config(m)' and 'csv_write(ap_list)').
I'm using Python 3.11 and latest pip and ncclient.
Could this be something related to proper namespace? https://github.com/ncclient/ncclient/issues/489
I have added the proper namespace to <config> but still failing and returning error:

```
C:\Cisco_c9800_netconf>\Python\Python311\python.exe get_config.py
** Starting Python script...

Traceback (most recent call last):
  File "C:\Cisco_c9800_netconf\get_config.py", line 274, in <module>
    main()
  File "C:\Cisco_c9800_netconf\get_config.py", line 254, in main
    ap_list = get_tags_config(m)
              ^^^^^^^^^^^^^^^^^^
  File "C:\Cisco_c9800_netconf\get_config.py", line 94, in get_tags_config
    result = m.get(filter)
             ^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\ncclient\manager.py", line 246, in execute
    return cls(self._session,
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\ncclient\operations\retrieve.py", line 91, in request
    return self._request(node)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\ncclient\operations\rpc.py", line 375, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-element', 'app_tag': None, 'severity': 'error', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><bad-element>filter</bad-element>\n</error-info>\n', 'path': '\n    /rpc/get\n  ', 'message': None}
```
Another error:
```
C:\Users\Cisco_c9800_netconf>\Python\Python311\python.exe get_config.py
** Starting Python script...

Traceback (most recent call last):
  File "C:\Cisco_c9800_netconf\get_config.py", line 274, in <module>
    main()
  File "C:\Cisco_c9800_netconf\get_config.py", line 257, in main
    csv_write(ap_list)
              ^^^^^^^
NameError: name 'ap_list' is not defined
```

**Comment by JesusPavonCBRE** [comment]
I've partially fixed the error modifying these lines:
```
line 84:     <filter xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
line 149:     <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
line 201:     <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">

```
Now the file is writen but no AP info inside:
```
</rpc-reply>

NETCONF AP tag configuration using get() method and XML filter:
<?xml version="1.0" ?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:a76aad4c-a1ba-4cfc-95ec-44b6ff0822bf">
        <data/>
</rpc-reply>


Writing AP tag configuration to CSV file named ap-tags-config-2023-05-09-10-48-30.csv:

** Time to run: 7.84 sec
```
